---
language: ruby
rvm:
- 2.2.5

install:
  - bundle install
  - sudo pip install pytest

script:
  - jekyll build
  - htmlproofer ./_site --allow-hash-href --internal-domains www.netsysops.io --http-status-ignore 999
  - cp _site-validation/site-validation.md _pages
  - jekyll build
  - pytest

after_success:
  - test $TRAVIS_BRANCH = "master" && curl -X POST --header "Fastly-Key: $FASTLY_API_TOKEN" https://api.fastly.com/service/$FASTLY_SERVICE/purge_all
